version: '3.9'
services:
  pdv:
    container_name: pdv
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql
      - migration
  migration:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: 'npx prisma migrate dev --name init'
    depends_on: 
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_TCP_PORT: $DB_PORT
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: