-- CreateTable
CREATE TABLE `TB_CLIENTE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(191) NOT NULL,
    `cpf` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `telefone` VARCHAR(191) NULL,
    `endereco` VARCHAR(191) NULL,
    `DATA-NASCIMENTO` DATETIME(3) NOT NULL,

    UNIQUE INDEX `TB_CLIENTE_cpf_key`(`cpf`),
    UNIQUE INDEX `TB_CLIENTE_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_VENDEDOR` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `cpf` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `nome` VARCHAR(191) NOT NULL,
    `telefone` VARCHAR(191) NULL,
    `endereco` VARCHAR(191) NULL,
    `dataNascimento` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Vendedor_cpf_key`(`cpf`),
    UNIQUE INDEX `Vendedor_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_NOTA_FISCAL` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clienteId` INTEGER NOT NULL,
    `vendedorId` INTEGER NOT NULL,
    `codigoProduto` VARCHAR(191) NOT NULL,
    `nomeProduto` VARCHAR(191) NOT NULL,
    `unidadeMedida` VARCHAR(191) NOT NULL,
    `grupoProduto` VARCHAR(191) NOT NULL,
    `valorProduto` DOUBLE NOT NULL,
    `registroFiscal` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_NOTA_FISCAL_ENTRATDA` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(191) NOT NULL,
    `cpf` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `telefone` VARCHAR(191) NULL,
    `endereco` VARCHAR(191) NULL,
    `DATA-NASCIMENTO` DATETIME(3) NOT NULL,

    UNIQUE INDEX `TB_NOTA_FISCAL_ENTRATDA_cpf_key`(`cpf`),
    UNIQUE INDEX `TB_NOTA_FISCAL_ENTRATDA_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_CONTAGEM_MENSAL` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(191) NOT NULL,
    `cpf` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `telefone` VARCHAR(191) NULL,
    `endereco` VARCHAR(191) NULL,
    `DATA-NASCIMENTO` DATETIME(3) NOT NULL,

    UNIQUE INDEX `TB_CONTAGEM_MENSAL_cpf_key`(`cpf`),
    UNIQUE INDEX `TB_CONTAGEM_MENSAL_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE TB_PRODUTO_SOLICITACAO(
   ID INT PRIMARY KEY,
   ID_SOLICITACAO_COMPRA INT,
   ID_PRODUTO INT
);

CREATE TABLE TB_REGISTRO_PRODUTOS(
    ID INT PRIMARY KEY,
    NOME VARCHAR(150),
    DESC_PROD VARCHAR(150),
    MARCA VARCHAR(150),
    UNIDADE_MEDIDA VARCHAR(150),
    ESTOQUE_ATUAL VARCHAR(150),
    PRECO DOUBLE NOT NULL,
    FORNECEDOR VARCHAR(150),
    CODIGO_PRODUTO VARCHAR(150),
    DATA_CADASTRO TIMESTAMP
);

CREATE TABLE TB_SOLICITACAO_COMPRA (
   ID INT PRIMARY KEY,
   ID_CLIENTE INT,
   ID_VENDEDOR INT
);

CREATE TABLE TB_USUARIO(
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(150),
    SENHA VARCHAR(150),
    NOME VARCHAR(150),
    ENDERECO VARCHAR(150),
    DATA_NASCIMENTO TIMESTAMP,
    CPF VARCHAR(11),
    TELEFONE VARCHAR(13),
    ID_ROLE INT
);

CREATE TABLE TB_ROLES (
    ID INT PRIMARY KEY,
    NOME VARCHAR(150)
);